<?php

namespace Blog\PublicationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    public function getPublicationsWithParams($search, $limit = 10, $from = 1, $order = null)
    {
        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->setFirstResult( $from )
            ->setMaxResults( $limit );

        if($order !== null)
           $query->orderBy('p.' . $order[0], $order[1]);

        if($search)
            $query->where($query->expr()->like('p.title', ':search'))
                ->setParameter('search', '%' . $search . '%');

        return $query->getQuery()->getResult();
    }

    public function getCount($category_id = null)
    {
        $query = $this->createQueryBuilder('p')
            ->select('COUNT(p.id)');

        if($category_id)
            $query->where('p.category_id = :category_id')
                ->setParameter('category_id', $category_id);

        return $query->getQuery()->getOneOrNullResult();
    }

    public function getPage($category_id = null)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM BlogPublicationsBundle:Publication p
                WHERE p.category = :category_id
                ORDER BY p.created DESC'
            )->setParameter('category_id', $category_id);

        return $query;
    }
}
