admin_panel_homepage:
    path:     /dashboard
    defaults: { _controller: AdminPanelBundle:Default:index }

admin_panel_config:
    path:     /config
    defaults: { _controller: AdminPanelBundle:Config:index }

admin_panel_blog:
    path:     /blog
    defaults: { _controller: AdminPanelBundle:Categories:index }

admin_panel_categories:
    path:     /blog/categories
    defaults: { _controller: AdminPanelBundle:Categories:index }

admin_panel_themes:
    path:     /blog/themes
    defaults: { _controller: AdminPanelBundle:Themes:index }

admin_panel_publications:
    path:     /blog/publications
    defaults: { _controller: AdminPanelBundle:Publications:index }

admin_publication_edit_exist_publication:
    path:     /publications/edit/{id}
    defaults: { _controller: AdminPanelBundle:Publications:edit, id: '' }

admin_article_delete:
    path:     /article/delete/{id}
    defaults: { _controller: AdminPanelBundle:Publications:delete }

admin_theme_delete:
    path:     /theme/delete/{id}
    defaults: { _controller: AdminPanelBundle:Themes:delete }
