services:
#    admin_panel.example:
#        class: Admin\PanelBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    admin.panel.menu.voter.request:
        class: Admin\PanelBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
