home:
    path: /
    defaults: { _controller: AppBundle:Default:index }

ajax:
    path: /ajax
    defaults: { _controller: AppBundle:Default:ajax }

route:
    path: /route
    defaults: { _controller: AppBundle:Default:route }