<?php

namespace Profile\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsersWithParams($search, $limit = 10, $from = 1, $order = null)
    {
        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->setFirstResult( $from )
            ->setMaxResults( $limit );

        if($order !== null)
            $query->orderBy('p.' . $order[0], $order[1]);

        if($search)
            $query->where($query->expr()->like('p.name', ':search'))
                ->setParameter('search', '%' . $search . '%');

        return $query->getQuery()->getResult();
    }

    public function getCount()
    {
        $query = $this->createQueryBuilder('p')
            ->select('COUNT(p.id)');

        return $query->getQuery()->getOneOrNullResult();
    }

}
